# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# 2020/07/24

image: docker:git
services:
  - docker:dind

stages:
  - build
  - sentry

build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      --build-arg=BUILD_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
      --build-arg MAINTAINER="$GITLAB_USER_EMAIL"
      -t $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:php7.4-apache
      .
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:php7.4-apache $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:php7.4-apache
