

services:
  wordpress:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: default_wp
      WORDPRESS_DB_PASSWORD: default_wp
      WORDPRESS_DB_NAME: default_wp
      WEBSERVER_HOST: webserver
      WORDPRESS_CONFIG_EXTRA: |
           define('WP_SITEURL', 'https://wp.demo.oibi.dev');
           define('WP_HOME', 'https://wp.demo.oibi.dev');
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`fpm.wp.demo.oibi.dev`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=9000"
    depends_on:
      - database

  webserver:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wp.demo.oibi.dev`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  database:
    image: mariadb:11.4
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default_wp
      - MYSQL_USER=default_wp
      - MYSQL_PASSWORD=default_wp
      - MYSQL_ROOT_PASSWORD=roowpwd7!!Jjjj

volumes:
  wordpress_data:
  database_data:
  