
services:
  wordpress:
    image: registry.oibi.dev/wordpress/fpm:latest
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WEBSERVER_HOST: webserver
      WORDPRESS_CONFIG_EXTRA: |
           define('WP_SITEURL', 'https://${SITE_DOMAIN}');
           define('WP_HOME', 'https://${SITE_DOMAIN}');
           define('WP_CACHE', true);
           define('WP_REDIS_HOST', 'redis');
#           define('WP_DEBUG_LOG', true);
    depends_on:
      - database
    networks:
      - traefik2_default
      - database_network
      - wordpress_network

  webserver:
    image: nginx:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress_nginx.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.wordpress_nginx.tls=true"
      - "traefik.http.routers.wordpress_nginx.tls.certresolver=le"
      - "traefik.http.services.wordpress_nginx.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network
      - traefik2_default

  database:
    image: mariadb:11.5
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - database_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - wordpress_network


volumes:
  wordpress_data:
  database_data:

networks:
  database_network:
  wordpress_network:
  traefik2_default:
    external: true