name: Build and Push Docker image

on:
  push:
    branches:
      - fpm

env:
  REGISTRY: registry.oibi.dev
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Set Environment Variables
        run: |
          echo "BUILD_DATE=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(date --utc +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
          echo "IMAGE_NAME_LOWER=$(echo '${{ github.repository }}' | cut -d '/' -f 2 | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}/${{ env.BRANCH_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}/${{ env.BRANCH_NAME }}:${{ env.BUILD_VERSION }}
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            CI_COMMIT_SHA=${{ github.sha }}
            MAINTAINER=${{ github.actor }}

      - name: Logout from Docker Registry
        run: docker logout ${{ env.REGISTRY }}

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}/${{ env.BRANCH_NAME }}:latest
